### ISSUE TITLE
Where did you get the thunderbolt board?

### ISSUE THREAD

**Issue by likaigelikaige** [teknoman117/ACORN-CLE-DVI#2]
RT, it's pleased to give more information about the thunderbolt board, thanks a lot.

**Comment by teknoman117** [comment]
It's a Sabrent thunderbolt 3 M.2 enclosure I got from Amazon. Note that it is only a 2-lane PCIe 3.0 interface so the PCIe interface is limited to 1 GB/s.

https://www.amazon.com/gp/product/B08FT59SB6
